# Taller 3
Presentado por
### Victor Manuel Dávila
### Oscar Javier Restrepo
### Daniel Lozano Barrero

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [7]:
img = cv2.imread('test.png')

height, width, channels = img.shape

def hitOrMiss(A, B):
    B1 = np.copy(B)
    B2 = np.copy(B)

    for i in range(len(B1)):
        for j in range(len(B1[0])):
            if B1[i][j] == 'x': B1[i][j] = 0

    for i in range(len(B2)):
        for j in range(len(B2[0])):
            if B2[i][j] == 'x' or B2[i][j] == '1': B2[i][j] = 0
            elif B2[i][j] == '0': B2[i][j] = 1

    A_c = cv2.bitwise_not(A)
    HM1 = cv2.erode(A, B1, 1)
    HM2 = cv2.erode(A_c, B2, 1)
    HM = cv2.bitwise_and(HM1, HM2)

    return HM

def thinning(A):
    B = cv2.getStructuringElement(cv2.MORPH_RECT, (7, 5), (3, 1))
    HM = hitOrMiss(A, B)
    thinned = A - HM
    return thinned

thinned = thinning(img)

cv2.imshow('Original', img)
cv2.waitKey()
cv2.imshow('Adelgazada', thinned)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[37  0 21]
  [38  1 22]
  [40  3 24]
  ...
  [12  0  0]
  [11  0  0]
  [11  0  0]]

 [[37  3 21]
  [38  4 22]
  [39  5 23]
  ...
  [12  0  0]
  [12  0  0]
  [12  0  0]]

 [[37  3 21]
  [38  4 22]
  [39  5 23]
  ...
  [13  1  1]
  [13  1  1]
  [13  1  1]]

 ...

 [[49 42 34]
  [49 42 34]
  [48 41 33]
  ...
  [ 9  0  0]
  [10  1  1]
  [10  1  1]]

 [[49 42 34]
  [49 42 34]
  [48 41 33]
  ...
  [ 8  0  0]
  [ 9  1  1]
  [ 9  1  1]]

 [[55 41 33]
  [49 42 34]
  [48 41 33]
  ...
  [ 8  0  0]
  [ 9  1  1]
  [ 9  1  1]]]
